apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhello
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webhello
  template:
    metadata:
      labels:
        app: webhello
    spec:
      containers:
      - name: webhello
        image: bstashchuk/k8s-web-hello
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
